// Bundle brand.ts + logos.gen.ts + scene.ts + figma-main.ts into one file (no imports) and compile it.
//  - figma-plugin/mirea-brand-guidelines/code.ts + code.js + ui.html + manifest.json  (local development plugin)
//  - build/mcp/code.ts + ui.html                                                       (Figma account-library plugin)
const fs = require('fs'); const path = require('path'); const cp = require('child_process');
const ROOT = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const MCP_PLUGIN_ID = 'bc0888f3-2b43-4bc8-89c1-abaf56262057';
const brand = read('src/brand.ts');
const imageFiles = JSON.stringify(eval('(' + brand.match(/const IMAGE_FILES[^=]*=\s*(\{[\s\S]*?\n\});/)[1] + ')'));
const header = (variant) => `// MIREA — Brand Guidelines Carousel · Figma plugin (${variant}).\n// GENERATED by tools/build_plugin.js from src/brand.ts, src/logos.gen.ts, src/scene.ts, src/figma-main.ts — edit the sources.\n`;
const logosFull = read('src/logos.gen.ts') + 'const LOGO_RUNTIME = false;\n';
// Account-library build: the logo artwork (40 KB of path data) is downloaded by the plugin window instead of being embedded.
const logoMan = JSON.parse(read('assets/logo/logo-manifest.json'));
const logoStub = '// Logo artwork is downloaded at run time (see ui.html); only the sizes are embedded.\ninterface LogoArt { w: number; h: number; svg: string }\nconst LOGO_FILL = \'#6A4937\';\nconst LOGO_RUNTIME = true;\nconst LOGOS: { [id: string]: LogoArt } = {\n' +
  Object.keys(logoMan).map((id) => '  ' + id + ': { w: ' + logoMan[id].width + ', h: ' + logoMan[id].height + ', svg: \'\' },').join('\n') + '\n};\n';
const logoFiles = JSON.stringify(Object.fromEntries(Object.keys(logoMan).map((id) => [id, 'assets/logo/' + logoMan[id].file])));
const bundle = (logos) => [read('src/brand.ts'), logos, read('src/scene.ts'), read('src/figma-main.ts')].join('\n');
const body = bundle(logosFull);
const bodyMcp = bundle(logoStub);
const SLIDE_COUNT = require(path.join(ROOT, 'build', 'scene.node.js')).buildSlides().length;
const uiBase = read('src/ui.html').replace('__IMAGE_FILES__', imageFiles).split('__SLIDE_COUNT__').join(String(SLIDE_COUNT));
const ui = uiBase.replace('__LOGO_FILES__', '{}').replace('__LOGO_HINT__', '');
const uiMcp = uiBase.replace('__LOGO_FILES__', logoFiles).replace('__LOGO_HINT__', ' The five logo vectors are always downloaded from the Base URL.');
for (const b of [body, bodyMcp]) if (/\bimport\b|\bexport\b/.test(b.replace(/\/\/.*$/gm, '').replace(/'[^']*'|"[^"]*"/g, ''))) throw new Error('bundle must not contain import/export');

// local plugin
const local = path.join(ROOT, 'figma-plugin', 'mirea-brand-guidelines');
fs.mkdirSync(local, { recursive: true });
fs.writeFileSync(path.join(local, 'code.ts'), header('local development build') + body.split('__RELAUNCH_COMMAND__').join('build'));
fs.writeFileSync(path.join(local, 'ui.html'), ui);
fs.writeFileSync(path.join(local, 'manifest.json'), JSON.stringify({
  name: 'MIREA Brand Guidelines Carousel', id: 'mirea-brand-guidelines-local', api: '1.0.0', main: 'code.js', ui: 'ui.html',
  editorType: ['figma'], documentAccess: 'dynamic-page',
  networkAccess: { allowedDomains: ['https://raw.githubusercontent.com'], reasoning: 'Downloads the packaging renders and paintings for the carousel from the project repository.' },
  relaunchButtons: [{ command: 'build', name: 'Build MIREA carousel' }],
}, null, 2) + '\n');
// MCP (account library) variant: relaunch command is the plugin id
const mcp = path.join(ROOT, 'build', 'mcp');
fs.mkdirSync(mcp, { recursive: true });
fs.writeFileSync(path.join(mcp, 'code.ts'), header('account-library build') + bodyMcp.split('__RELAUNCH_COMMAND__').join(MCP_PLUGIN_ID));
fs.writeFileSync(path.join(mcp, 'ui.html'), uiMcp);
// type-check + emit
for (const [src, out] of [[path.join(local, 'code.ts'), path.join(local, 'code.js')], [path.join(mcp, 'code.ts'), path.join(mcp, 'code.js')]]) {
  const r = cp.spawnSync('npx', ['tsc', src, '--target', 'ES2019', '--lib', 'ES2019', '--types', '@figma/plugin-typings', '--strict', '--noEmitOnError', '--outFile', out], { cwd: ROOT, encoding: 'utf8' });
  if (r.status !== 0) { console.error(r.stdout, r.stderr); process.exit(1); }
  console.log('compiled', path.relative(ROOT, out), fs.statSync(out).size, 'bytes');
}
// Figma rejects plugin code containing the sequence "eval(" in some loaders — make sure none slipped in.
for (const f of [path.join(local, 'code.js'), path.join(mcp, 'code.ts')]) if (/\beval\s*\(/.test(fs.readFileSync(f, 'utf8'))) throw new Error('eval( found in ' + f);
console.log('slides', SLIDE_COUNT, '· ui.html', ui.length, 'bytes · mcp ui.html', uiMcp.length, 'bytes · mcp code.ts', fs.statSync(path.join(mcp, 'code.ts')).size, 'bytes');
