// Bundle brand.ts + logos.gen.ts + scene.ts + figma-main.ts into one file (no imports) and compile it.
//  - figma-plugin/mirea-brand-guidelines/code.ts + code.js + ui.html + manifest.json  (local development plugin)
//  - build/mcp/code.ts + ui.html                                                       (Figma account-library plugin)
const fs = require('fs'); const path = require('path'); const cp = require('child_process');
const ROOT = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const MCP_PLUGIN_ID = 'bc0888f3-2b43-4bc8-89c1-abaf56262057';
const brand = read('src/brand.ts');
const imageFiles = JSON.stringify(eval('(' + brand.match(/const IMAGE_FILES[^=]*=\s*(\{[\s\S]*?\n\});/)[1] + ')'));
const header = (variant) => `// MIREA — Brand Guidelines Carousel · Figma plugin (${variant}).\n// GENERATED by tools/build_plugin.js from src/brand.ts, src/logos.gen.ts, src/scene.ts, src/figma-main.ts — edit the sources.\n`;
const body = [read('src/brand.ts'), read('src/logos.gen.ts'), read('src/scene.ts'), read('src/figma-main.ts')].join('\n');
const ui = read('src/ui.html').replace('__IMAGE_FILES__', imageFiles);
if (/\bimport\b|\bexport\b/.test(body.replace(/\/\/.*$/gm, '').replace(/'[^']*'|"[^"]*"/g, ''))) throw new Error('bundle must not contain import/export');

// local plugin
const local = path.join(ROOT, 'figma-plugin', 'mirea-brand-guidelines');
fs.mkdirSync(local, { recursive: true });
fs.writeFileSync(path.join(local, 'code.ts'), header('local development build') + body.split('__RELAUNCH_COMMAND__').join('build'));
fs.writeFileSync(path.join(local, 'ui.html'), ui);
fs.writeFileSync(path.join(local, 'manifest.json'), JSON.stringify({
  name: 'MIREA Brand Guidelines Carousel', id: 'mirea-brand-guidelines-local', api: '1.0.0', main: 'code.js', ui: 'ui.html',
  editorType: ['figma'], documentAccess: 'dynamic-page',
  networkAccess: { allowedDomains: ['https://raw.githubusercontent.com'], reasoning: 'Downloads the packaging renders and paintings for the carousel from the project repository.' },
  relaunchButtons: [{ command: 'build', name: 'Build MIREA carousel' }],
}, null, 2) + '\n');
// MCP (account library) variant: relaunch command is the plugin id
const mcp = path.join(ROOT, 'build', 'mcp');
fs.mkdirSync(mcp, { recursive: true });
fs.writeFileSync(path.join(mcp, 'code.ts'), header('account-library build') + body.split('__RELAUNCH_COMMAND__').join(MCP_PLUGIN_ID));
fs.writeFileSync(path.join(mcp, 'ui.html'), ui);
// type-check + emit
for (const [src, out] of [[path.join(local, 'code.ts'), path.join(local, 'code.js')], [path.join(mcp, 'code.ts'), path.join(mcp, 'code.js')]]) {
  const r = cp.spawnSync('npx', ['tsc', src, '--target', 'ES2019', '--lib', 'ES2019', '--types', '@figma/plugin-typings', '--strict', '--noEmitOnError', '--outFile', out], { cwd: ROOT, encoding: 'utf8' });
  if (r.status !== 0) { console.error(r.stdout, r.stderr); process.exit(1); }
  console.log('compiled', path.relative(ROOT, out), fs.statSync(out).size, 'bytes');
}
// Figma rejects plugin code containing the sequence "eval(" in some loaders — make sure none slipped in.
for (const f of [path.join(local, 'code.js'), path.join(mcp, 'code.ts')]) if (/\beval\s*\(/.test(fs.readFileSync(f, 'utf8'))) throw new Error('eval( found in ' + f);
console.log('ui.html', ui.length, 'bytes');
